config/routes.rb
Community::Application.routes.draw do

  resources :categories, :except => [:index, :show]
  resources :microposts
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
  
  devise_for :users
  root :to => 'categories#index', :via => :get

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  # Associations
  has_many :posts, :dependent => :destroy
  belongs_to :forum, :counter_cache => true
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked, :forum_id
  
  # Validations
  validates :title,   :presence => true
  validates :body,    :presence => true, :on => :create
  validates :posts,   :presence => true, :allow_nil => false, :on => :update
  validates :user,    :presence => true
  
  # Scopes
  default_scope :order => 'sticky DESC, updated_at DESC'
  
  # Callbacks
  after_create :create_initial_post
  
  # Methods
  def hit!
    self.class.increment_counter :hits, id
  end
  
  private
    def create_initial_post
      returning self.posts.build(:body => self.body) do |post|
        post.forum = self.forum
        post.user = self.user
        post.save
      end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource :forum
  load_and_authorize_resource :topic, :through => :forum, :shallow => true
  
  def show
    @topic.hit! if @topic
  end
  
  def create
    @topic.user ||= current_user
    
    if @topic.save
      flash[:notice] = "Topic was successfully created."
      redirect_to topic_url(@topic)
    else
      render :action => 'new'
    end
  end
  
  def update
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic was updated successfully."
      redirect_to topic_url(@topic)
    end
  end

  def destroy
    if @topic.destroy
      flash[:notice] = "Topic was deleted successfully."
      redirect_to forum_url(@topic.forum)
    end
  end
  
end

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |f| %>
<% if @topic.errors.any? %>
  <% flash.now[:error] = @topic.errors.full_messages.join(', and ') %>
<% end %>
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Topic</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <% unless @topic.id %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :body %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :body, :cols => 60, :rows => 15 %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", @topic.new_record? ?  @forum : @topic %></span>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/topics/edit.html.erb
<%= render :partial => 'form' %>

app/views/topics/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<div class="right controls"><%= link_to "Back to Forum", forum_path(@topic.forum) %></div>
<div class="module">
  <div class="module_header">
    <%= @topic.title %>
    <span class="right controls">
      <%= link_to "Edit", edit_topic_path(@topic) if can? :manage, @topic %>
      <%= link_to "Delete", @topic, :confirm => "Are you sure?", :method => :delete if can? :manage, @topic %>
      <%= link_to @topic.sticky ? "Unstick" : "Sticky", {:controller => 'topics', :action => 'update', :topic => {:sticky => @topic.sticky ? "false" : "true" }}, :method => :put if can? :moderate, @topic %>
      <%= link_to @topic.locked ? "Unlock" : "Lock", {:controller => 'topics', :action => 'update', :topic => {:locked => @topic.locked ? "false" : "true" }}, :method => :put if can? :moderate, @topic %>
    </span>
  </div>
  <div>
    <table>
      <% @topic.posts.each do |post| %>
      <tr>
        <td class="post_author" rowspan="2">
          <span class="name"><%= post.user.username %></span>
          <span class="avatar"><%= image_tag post.user.gravatar_url %></span>
          <span class="info smaller">
            <p><strong><%= "Administrator" if post.user.admin? %></strong></p>
            Posts <%= post.user.posts.size %><br />
            Registered <%=l post.user.created_at, :format => :joined %><br />
          </span>
        </td>
        <td class="post_header">
          <span class="left post_date smaller">Posted <%=l post.created_at %></span>
          <span class="right controls">
            <%= link_to "Reply", new_topic_post_path(@topic) if can? :create, @topic.posts.new %>
            <%= link_to "Quote", new_topic_post_path(@topic, :quote => post) if can? :create, @topic.posts.new %>
            <%= link_to "Edit", edit_post_path(post) if can? :update, post %>
            <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete if can? :destroy, post %>
          </span>
        </td>
      </tr>
      <tr>
        <td class="post_body">
          <%= post.body.bbcode_to_html().html_safe %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="right controls"><p><%= link_to "Back to Forum", forum_path(@topic.forum) %></p></div>