config/routes.rb
Community::Application.routes.draw do

  resources :categories, :except => [:index, :show]
  resources :microposts
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
  
  devise_for :users
  root :to => 'categories#index', :via => :get

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource :category
  
  def create
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to forums_url
    else
      render :action => 'new'
    end
  end
  
  def update    
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category was updated successfully."
      redirect_to forums_url
    end
  end
  
  def destroy
    if @category.destroy
      flash[:notice] = "Category was deleted."
      redirect_to forums_url
    end
  end
end

app/views/categories/_form.html.erb
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Category</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <%= form_for @category do |f| %>
      <% if @category.errors.any? %>
        <% flash.now[:error] = @category.errors.full_messages.join(', and ') %>
      <% end %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :position %>
        </span>
        <span class="input indent smaller"><%= f.text_field :position %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller"></span>
        <span class="input indent smaller">
          <%= f.check_box :state %>
          <%= f.label :state %>
        </span>
        <div class="clear"></div>
      </div>
    </div>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", forums_path %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<div class="right controls"><%= link_to "New Forum Category", new_category_path if can? :create, Category %></div>

<% @categories.each do |category| %>
  <div class="module">
    <div class="module_header">
      <%= category.title %>
      <span class="controls right smaller">
        <%= link_to "New Forum", new_forum_path if can? :create, Forum %>
        <%= link_to "Edit Category", edit_category_path(category) if can? :manage, category %>
        <%= link_to "Delete Category", category_path(category), :confirm => "Are you sure you want to delete this category?", :method => :delete if can? :manage, category %>
      </span>
    </div>
    <% if category.forums.size > 0 %>
    <div>
      <table>
        <tr class="smaller">
          <th colspan="2" align="left">Forum</th>
          <th>Topics</th>
          <th>Posts</th>
          <th class="last_post" align="left">Last Post</th>
        </tr>
        <% category.forums.each do |forum| %>
        <tr>
          <td class="icon"><%= image_tag 'fle-brun.jpg' %></td>
          <td class="description">
            <%= link_to forum.title, forum_path(forum) %><br />
            <span class="smaller"><%= forum.description %></span><br />
          </td>
          <td class="counts smaller"><%= forum.topics.size %></td>
          <td class="counts smaller"><%= forum.posts.size - forum.topics.size %></td>
          <td class="last_post smaller">
            <% if forum.posts.size > 0 %>
              <%=l forum.posts.last.created_at %><br />
              <%= forum.posts.last.user.username %>
            <% else %>
              No Topics / Posts
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <% else %>
      <div class="module_body">There are currently no forums.</div>
    <% end %>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>